name: Ruby

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby-version }}
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.4']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
          
      - name: Run tests
        run: bundle exec rake test
        
      - name: Run RuboCop
        run: bundle exec rubocop --parallel
        if: matrix.ruby-version == '3.4'
